#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

composer install

php artisan key:gen
php artisan migrate --force

npm ci && npm run build

chown -R $(whoami) .
chmod -R 777 ./bootstrap/cache/
chmod -R 777 ./storage

php artisan route:clear
php artisan view:clear
php artisan config:clear

php artisan route:cache
php artisan view:cache
php artisan config:cache

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
